#!/usr/bin/env bash
DNS=$(aws elbv2 describe-load-balancers --names ecommerce-monolith-ecs-alb --query 'LoadBalancers[0].DNSName')
echo "Access App at $DNS"

# The open command only works on macOS
if [ `uname -s` == "Darwin" ]; then
  open "$DNS"
fi
